export const menus = [
       {'name': 'Mantenimiento Menu',
      'icon': 'widgets',
      'link': false,
      'open': false,
      'sub': [
        {
          'name': 'Menu s/ 9',
          'link': 'restaurant/menu1',
          'icon': 'indeterminate_check_box',
          'chip': false,
          'open': false,
        },

        {
          'name': 'Menu s/ 12',
          'link': 'restaurant/menu2',
          'icon': 'indeterminate_check_box',
          'chip': false,
          'open': false,
        }
      ]},
  {'name': 'Mantenimiento Carta',
  'icon': 'widgets',
  'link': false,
  'open': false,
  'sub': [{
    'name': 'Carta Marina',
    'link': 'restaurant/cartaMarina',
    'icon': 'indeterminate_check_box',
    'chip': false,
    'open': false,
  },
  {
    'name': 'Carta Criolla',
    'link': 'restaurant/cartaCriolla',
    'icon': 'indeterminate_check_box',
    'chip': false,
    'open': false,
  },
  {
    'name': 'Pollo A la Brasa',
    'link': 'restaurant/polloBrasa',
    'icon': 'indeterminate_check_box',
    'chip': false,
    'open': false,
  },
  {
    'name': 'Postre',
    'link': 'restaurant/postre',
    'icon': 'indeterminate_check_box',
    'chip': false,
    'open': false,
  },
  {
    'name': 'Parrillas',
    'link': 'restaurant/parrilla',
    'icon': 'indeterminate_check_box',
    'chip': false,
    'open': false,
  }
]},
  {'name': 'Mantenimiento Bebidas',
  'icon': 'widgets',
  'link': false,
  'open': false,
  'sub': [
    {
      'name': 'Gaseosa',
      'link': 'restaurant/gaseosa',
      'icon': 'indeterminate_check_box',
      'chip': false,
      'open': false,
    },
    {
      'name': 'Bebida',
      'link': 'restaurant/bebida',
      'icon': 'indeterminate_check_box',
      'chip': false,
      'open': false,
    },
    {
      'name': 'Barban',
      'link': 'restaurant/barban',
      'icon': 'indeterminate_check_box',
      'chip': false,
      'open': false,
    }
  ]},
  {'name': 'Mantenimiento Entradas',
  'icon': 'widgets',
  'link': false,
  'open': false,
  'sub': [
    {
      'name': 'Entradas',
      'link': 'restaurant/entradas',
      'icon': 'indeterminate_check_box',
      'chip': false,
      'open': false,
    }]},
    {'name': 'Control',
      'icon': 'widgets',
      'link': false,
      'open': false,
      'sub': [{
        'name': 'Cierre Caja',
        'link': 'restaurant/cierrecaja',
        'icon': 'indeterminate_check_box',
        'chip': false,
        'open': false,
      },
      {
        'name': 'Cuadre Caja',
        'link': 'restaurant/cuadreCaja',
        'icon': 'indeterminate_check_box',
        'chip': false,
        'open': false,
      },
      {
        'name': 'Empleados',
        'link': 'restaurant/empleado',
        'icon': 'indeterminate_check_box',
        'chip': false,
        'open': false,
      },
      {
        'name': 'Venta',
        'link': 'restaurant/venta',
        'icon': 'indeterminate_check_box',
        'chip': false,
        'open': false,
      },
      {
        'name': 'Ranking',
        'link': 'restaurant/ranking_pollo',
        'icon': 'indeterminate_check_box',
        'chip': false,
        'open': false,
      }]},
      {'name': 'Mantenimiento Principal',
      'icon': 'widgets',
      'link': false,
      'open': false,
      'sub': [
        {
          'name': 'Mesa',
          'link': 'restaurant/mesa',
          'icon': 'indeterminate_check_box',
          'chip': false,
          'open': false,
      },
      {
        'name': 'Plato',
        'link': 'restaurant/plato',
        'icon': 'indeterminate_check_box',
        'chip': false,
        'open': false,
    },
    {
      'name': 'Categorias',
      'link': 'restaurant/categoria',
      'icon': 'indeterminate_check_box',
      'chip': false,
      'open': false,
    },
    {
      'name': 'Mesa Crud',
      'link': 'restaurant/mesaCrud',
      'icon': 'indeterminate_check_box',
      'chip': false,
      'open': false,
    },
    {
      'name': 'Carta',
      'link': 'restaurant/carta',
      'icon': 'indeterminate_check_box',
      'chip': false,
      'open': false,
    }
      ]},
];
